name: vdrift # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2018.11.28' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Car Racing Simulator for Multiple Platforms # 79 char long summary
description: VDrift is a cross-platform, open source driving simulation made with drift racing in mind. It is released under the [GNU General Public License (GPL) v3](http://www.gnu.org/licenses/gpl-3.0.en.html).It is currently available for FreeBSD, Linux, Mac OS X and Windows.

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: scons
    source-type: 7z
    source: https://netcologne.dl.sourceforge.net/project/vdrift/vdrift/nightly%20builds/vdrift-2015-11-28.7z
    build-packages:
      - g++
      - scons
      - subversion
      - libbullet-dev
      - libcurl4-gnutls-dev
      - libvorbis-dev
      - libsdl2-dev
      - libsdl2-image-dev
